######################################################################
# Automatically generated by qmake (3.0) Thu Apr 14 22:08:25 2016
######################################################################

TEMPLATE = app
TARGET = finalSubmit
INCLUDEPATH += .

# Input
HEADERS += delay.h OledChar.h OledGrph.h PmodOLED.h
SOURCES += ChrFont0.c \
           delay.c \
           FillPat.c \
           OledChar.c \
           OledGrph.c \
           PmodOLED.c \
           zhao_lab3.c
